# Generated by Django 4.2.7 on 2026-01-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template Name"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("weight_gain", "Weight Gain"),
                            ("muscle_building", "Muscle Building"),
                        ],
                        max_length=20,
                        verbose_name="Goal Type",
                    ),
                ),
                ("calorie_min", models.IntegerField(verbose_name="Minimum Calories")),
                ("calorie_max", models.IntegerField(verbose_name="Maximum Calories")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("meals_data", models.JSONField(verbose_name="Meals Data")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Diet Plan Template",
                "verbose_name_plural": "Diet Plan Templates",
                "db_table": "diet_plan_template",
                "ordering": ["goal_type", "calorie_min"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Food Name")),
                (
                    "food_category",
                    models.CharField(
                        choices=[
                            ("dairy", "Dairy"),
                            ("seafood", "Seafood"),
                            ("nuts", "Nuts"),
                            ("eggs", "Eggs"),
                            ("grains", "Grains"),
                            ("vegetables", "Vegetables"),
                            ("fruits", "Fruits"),
                            ("meat", "Meat"),
                            ("legumes", "Legumes"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Calories (per 100g)",
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Protein (g)"
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Carbohydrates (g)"
                    ),
                ),
                (
                    "fats",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Fats (g)"
                    ),
                ),
                (
                    "serving_size",
                    models.CharField(
                        default="100g", max_length=50, verbose_name="Serving Size"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Food Item",
                "verbose_name_plural": "Food Items",
                "db_table": "food_item",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserDietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=100, verbose_name="Plan Name"),
                ),
                (
                    "target_calories",
                    models.IntegerField(verbose_name="Target Daily Calories"),
                ),
                ("meals_data", models.JSONField(verbose_name="Customized Meals")),
                ("notes", models.TextField(blank=True, verbose_name="Trainer Notes")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.dietplantemplate",
                        verbose_name="Template Used",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_diet_plans",
                        to="users.trainer",
                        verbose_name="Trainer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to="users.userlogin",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Diet Plan",
                "verbose_name_plural": "User Diet Plans",
                "db_table": "user_diet_plan",
                "ordering": ["-created_at"],
            },
        ),
    ]
