# Generated by Django 4.2.7 on 2026-01-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_dietplantemplate_fooditem_userdietplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="diet_type",
            field=models.CharField(
                choices=[
                    ("vegan", "Vegan"),
                    ("vegetarian", "Vegetarian"),
                    ("non_veg", "Non-Vegetarian"),
                ],
                default="vegan",
                max_length=20,
                verbose_name="Diet Type",
            ),
        ),
    ]
