# Generated by Django 4.2.7 on 2026-01-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(verbose_name="Quantity")),
                (
                    "quantity_unit",
                    models.CharField(
                        default="g",
                        max_length=50,
                        verbose_name="Unit (g, ml, piece, cup, bowl, etc.)",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snacks", "Snacks"),
                            ("fruits", "Fruits"),
                            ("nuts", "Nuts"),
                            ("milks", "Milks"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Meal Type",
                    ),
                ),
                (
                    "calculated_calories",
                    models.FloatField(verbose_name="Calculated Calories"),
                ),
                (
                    "is_custom_calories",
                    models.BooleanField(
                        default=False, verbose_name="Is Custom Default Calorie"
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="Entry Date")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="users.fooditem",
                        verbose_name="Food Item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_entries",
                        to="users.userlogin",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Entry",
                "verbose_name_plural": "Food Entries",
                "db_table": "food_entry",
                "ordering": ["-entry_date", "meal_type"],
                "indexes": [
                    models.Index(
                        fields=["user", "entry_date"],
                        name="food_entry_user_id_582fa2_idx",
                    )
                ],
            },
        ),
    ]
